### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by karan-kang** [pioug/md-virtual-repeater#2]
Hi, I tried to use this library in my application, but it does not work.

I have created a fiddle to demonstrate this issue, please let me know what I am doing wrong.
https://jsfiddle.net/karank007/gavqfagt/2/

**Comment by karan-kang** [comment]
Once i changed the CSS to this it started working, the one provided in ReadMe.md does not work:

> md-virtual-repeat-container {
>   height: 250px;
> }
> 
> md-virtual-repeat-container:-webkit-scrollbar {
>   width: 0 !important;
> }

**Comment by pioug** [comment]
Looks like the link of your JSFiddle is incorrect.
Anyway, you must specify dimension for `md-virtual-repeat-container` because it won't naturally "fill the space". The CSS for the scrollbar will work only for Safari/Chrome obviously. You can also check out the demo in the repo https://github.com/pioug/md-virtual-repeater/blob/gh-pages/index.html

**Comment by pioug** [comment]
Closing this. Feel free to reopen if anything.
